### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by chnaltn** [TomasPel/airflow_dbt_postgres#2]
Hello,

When I run docker-compose up command getting errors: 
- airflow_dbt_postgres-webserver-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2024-02-26'
- airflow_dbt_postgres-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2024-02-26'

**Comment by uncledata** [comment]
Hey, there were two options around this:
1. If you want logs -> grant permissions on logs folder with simple chmod command
2. Remove logs from being mounted in docker compose.

Currently I've taken the 2 option, since it will be out of the box solution for everybody using this repository.

**Comment by chnaltn** [comment]
In Dockerfile;

adding RUN chmod 777 /opt/airflow/logs line solved the issue.
